# Generated by Django 4.1.7 on 2023-03-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0003_user_avatar_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/img/blank-profile-picture.png', null=True, upload_to=''),
        ),
    ]
