# Generated by Django 4.1.7 on 2023-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='blank-profile-picture.png', null=True, upload_to=''),
        ),
    ]
