# Generated by Django 4.1.7 on 2023-03-19 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0005_rename_location_spot_city_spot_state_spot_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
