# Generated by Django 4.1.7 on 2023-04-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0005_spot_created_spot_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skatebooks.category'),
        ),
    ]
