# Generated by Django 4.1.7 on 2023-04-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0006_alter_spot_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hometown',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
