# Generated by Django 4.1.7 on 2023-03-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0006_user_hometown_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
