# Generated by Django 4.1.7 on 2023-04-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0007_alter_user_hometown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='blank-profile-picture.png', null=True, upload_to=''),
        ),
    ]
