# Generated by Django 4.1.7 on 2023-03-21 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0007_spot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
