# Generated by Django 4.1.7 on 2023-03-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0008_spot_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='image',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
