# Generated by Django 4.1.7 on 2023-03-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0009_alter_spot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
