# Generated by Django 4.1.7 on 2023-04-10 15:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='blank-profile-picture.png', max_length=255, null=True),
        ),
    ]
