# Generated by Django 4.1.7 on 2023-03-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0010_alter_spot_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ['-created']},
        ),
    ]
