# Generated by Django 4.1.7 on 2023-04-10 15:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0011_alter_spot_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatar', max_length=255, null=True),
        ),
    ]
