# Generated by Django 4.1.7 on 2023-03-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0012_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='num_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
