# Generated by Django 4.1.7 on 2023-04-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0016_remove_spot_lat_remove_spot_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
