# Generated by Django 4.1.7 on 2023-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0017_spot_lat_spot_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
