# Generated by Django 4.1.7 on 2023-04-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0018_spot_address_spot_latitude_spot_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='address',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='longitude',
        ),
    ]
