# Generated by Django 4.1.7 on 2023-04-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skatebooks', '0019_remove_spot_address_remove_spot_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='long',
        ),
    ]
